# Generated by Django 2.2.2 on 2019-06-09 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=75)),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('image', models.CharField(blank=True, max_length=50)),
                ('url_API', models.CharField(blank=True, max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personaje.Personaje')),
            ],
        ),
    ]
