# Generated by Django 2.2.2 on 2019-06-09 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 9, 22, 3, 6, 853566), null=True),
        ),
    ]
