# Generated by Django 2.2.2 on 2019-07-03 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_auto_20190703_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 3, 11, 50, 33, 416504)),
        ),
    ]
