# Generated by Django 2.2.2 on 2019-06-09 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_auto_20190609_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 9, 22, 4, 54, 331442)),
        ),
    ]
