# Generated by Django 2.2.2 on 2019-06-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=7)),
                ('mass', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=10)),
                ('eye_color', models.CharField(max_length=10)),
                ('birth_year', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N/A', 'N/a')], max_length=10)),
                ('image', models.CharField(blank=True, max_length=50)),
                ('url_API', models.CharField(blank=True, max_length=50)),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.Film')),
            ],
        ),
    ]
